TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

DEFINES += STM32F407xx USE_HAL_DRIVER ARM_MATH_CM4 __FPU_PRESENT

INCLUDEPATH += \
    ../Inc \
    ../Inc/uartcomm \
    ../Drivers/STM32F4xx_HAL_Driver/Inc \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
    ../Drivers/CMSIS/Include \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include \
    ../Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F \
    ../Middlewares/Third_Party/FreeRTOS/Source/include \
    ../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
    ../Middlewares/Third_Party/FatFs/src \
    ../Middlewares/Third_Party/FatFs/src/drivers \
    ../Middlewares/Third_Party/LwIP/src/include/lwip \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/priv \
    ../Middlewares/Third_Party/LwIP/src/include/netif \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot \
    ../Middlewares/Third_Party/LwIP/src/include/posix \
    ../Middlewares/Third_Party/LwIP/src/include \
    ../Middlewares/Third_Party/LwIP/system/arch \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps \
    ../Middlewares/Third_Party/LwIP/src/include/posix/sys

SOURCES += \
    ../Src/adc.c \
    ../Src/bsp_driver_sd.c \
    ../Src/dac.c \
    ../Src/dma.c \
    ../Src/ethernetif.c \
    ../Src/fatfs.c \
    ../Src/freertos.c \
    ../Src/gpio.c \
    ../Src/i2c.c \
    ../Src/lwip.c \
    ../Src/main.c \
    ../Src/sdio.c \
    ../Src/spi.c \
    ../Src/stm32f4xx_hal_msp.c \
    ../Src/stm32f4xx_hal_timebase_TIM.c \
    ../Src/stm32f4xx_it.c \
    ../Src/system_stm32f4xx.c \
    ../Src/tim.c \
    ../Src/usart.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dfsdm.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_lptim.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_mmc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_msp_template.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spdifrx.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_rtc_alarm_template.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_rtc_wakeup_template.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_tim_template.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_crc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dac.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma2d.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_i2c.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_lptim.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_pwr.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rng.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rtc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_spi.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_tim.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
    ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/list.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/queue.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/timers.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F/port.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c \
    ../Middlewares/Third_Party/FatFs/src/diskio.c \
    ../Middlewares/Third_Party/FatFs/src/ff.c \
    ../Middlewares/Third_Party/FatFs/src/ff_gen_drv.c \
    ../Middlewares/Third_Party/FatFs/src/drivers/sd_diskio.c \
    ../Middlewares/Third_Party/LwIP/src/core/def.c \
    ../Middlewares/Third_Party/LwIP/src/core/dns.c \
    ../Middlewares/Third_Party/LwIP/src/core/inet_chksum.c \
    ../Middlewares/Third_Party/LwIP/src/core/init.c \
    ../Middlewares/Third_Party/LwIP/src/core/ip.c \
    ../Middlewares/Third_Party/LwIP/src/core/mem.c \
    ../Middlewares/Third_Party/LwIP/src/core/memp.c \
    ../Middlewares/Third_Party/LwIP/src/core/netif.c \
    ../Middlewares/Third_Party/LwIP/src/core/pbuf.c \
    ../Middlewares/Third_Party/LwIP/src/core/raw.c \
    ../Middlewares/Third_Party/LwIP/src/core/stats.c \
    ../Middlewares/Third_Party/LwIP/src/core/sys.c \
    ../Middlewares/Third_Party/LwIP/src/core/tcp.c \
    ../Middlewares/Third_Party/LwIP/src/core/tcp_in.c \
    ../Middlewares/Third_Party/LwIP/src/core/tcp_out.c \
    ../Middlewares/Third_Party/LwIP/src/core/timeouts.c \
    ../Middlewares/Third_Party/LwIP/src/core/udp.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ethernet.c \
    ../Middlewares/Third_Party/LwIP/system/OS/sys_arch.c \
    ../Middlewares/Third_Party/LwIP/src/api/api_lib.c \
    ../Middlewares/Third_Party/LwIP/src/api/api_msg.c \
    ../Middlewares/Third_Party/LwIP/src/api/err.c \
    ../Middlewares/Third_Party/LwIP/src/api/netbuf.c \
    ../Middlewares/Third_Party/LwIP/src/api/netdb.c \
    ../Middlewares/Third_Party/LwIP/src/api/netifapi.c \
    ../Middlewares/Third_Party/LwIP/src/api/sockets.c \
    ../Middlewares/Third_Party/LwIP/src/api/tcpip.c \
    ../Src/quickSample.c \
    ../Src/networktask.c \
    ../Src/uartcomm/bufferred_uart.c \
    ../Src/uartcomm/debug_print.c \
    ../Src/uartcomm/putc_redirect.c \
    ../Src/rx8025/Rx8025.c \
    ../Src/gc-bsp.c \
    ../Src/keypad/keypad.c \
    ../Src/cs1238/cs1238.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/CommonTables/arm_common_tables.c \
    ../Drivers/CMSIS/DSP_Lib/Source/CommonTables/arm_const_structs.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_conj_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_conj_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_conj_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_dot_prod_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_squared_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_real_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_real_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_real_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_reset_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_reset_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_reset_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_sin_cos_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_sin_cos_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_cos_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_cos_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_cos_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sin_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sin_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sin_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sqrt_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sqrt_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_add_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_add_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_add_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_inverse_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_inverse_f64.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_fast_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_fast_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_scale_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_scale_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_scale_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_sub_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_sub_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_sub_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_trans_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_trans_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_trans_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_max_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_max_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_max_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_max_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_mean_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_mean_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_mean_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_mean_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_min_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_min_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_min_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_min_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_power_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_power_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_power_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_power_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_rms_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_rms_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_rms_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_std_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_std_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_std_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_var_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_var_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_var_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_copy_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_copy_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_copy_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_copy_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_fill_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_fill_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_fill_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_fill_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_float_to_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_float_to_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_float_to_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q15_to_float.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q15_to_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q15_to_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q31_to_float.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q31_to_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q31_to_q7.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q7_to_float.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q7_to_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q7_to_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_bitreversal.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix8_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_fast_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_fast_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_init_f32.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_init_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_init_q31.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_q15.c \
    ../Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_q31.c \
    ../Middlewares/Third_Party/FatFs/src/drivers/sdram_diskio.c \
    ../Middlewares/Third_Party/FatFs/src/drivers/sram_diskio.c \
    ../Middlewares/Third_Party/FatFs/src/drivers/usbh_diskio.c \
    ../Middlewares/Third_Party/FatFs/src/option/cc932.c \
    ../Middlewares/Third_Party/FatFs/src/option/cc936.c \
    ../Middlewares/Third_Party/FatFs/src/option/cc949.c \
    ../Middlewares/Third_Party/FatFs/src/option/cc950.c \
    ../Middlewares/Third_Party/FatFs/src/option/ccsbcs.c \
    ../Middlewares/Third_Party/FatFs/src/option/syscall.c \
    ../Middlewares/Third_Party/FatFs/src/option/unicode.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_1.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_2.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_3.c \
    ../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_5.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/dhcp6.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/ethip6.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/icmp6.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/inet6.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/ip6.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_addr.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_frag.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/mld6.c \
    ../Middlewares/Third_Party/LwIP/src/core/ipv6/nd6.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/polarssl/arc4.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/polarssl/des.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/polarssl/md4.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/polarssl/md5.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/polarssl/sha1.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/auth.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/ccp.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/chap-md5.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/chap-new.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/chap_ms.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/demand.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/eap.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/ecp.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/eui64.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/fsm.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/ipcp.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/ipv6cp.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/lcp.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/magic.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/mppe.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/multilink.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/ppp.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/pppapi.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/pppcrypt.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/pppoe.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/pppol2tp.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/pppos.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/upap.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/utils.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ppp/vj.c \
    ../Middlewares/Third_Party/LwIP/src/netif/ethernetif_template.c \
    ../Middlewares/Third_Party/LwIP/src/netif/lowpan6.c \
    ../Middlewares/Third_Party/LwIP/src/netif/slipif.c

HEADERS += \
    ../Inc/adc.h \
    ../Inc/bsp_driver_sd.h \
    ../Inc/dac.h \
    ../Inc/dma.h \
    ../Inc/ethernetif.h \
    ../Inc/fatfs.h \
    ../Inc/ffconf.h \
    ../Inc/FreeRTOSConfig.h \
    ../Inc/gpio.h \
    ../Inc/i2c.h \
    ../Inc/lwip.h \
    ../Inc/lwipopts.h \
    ../Inc/main.h \
    ../Inc/sdio.h \
    ../Inc/spi.h \
    ../Inc/stm32f4xx_hal_conf.h \
    ../Inc/stm32f4xx_it.h \
    ../Inc/tim.h \
    ../Inc/usart.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_can.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cec.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_conf_template.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cortex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_crc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cryp.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cryp_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dcmi.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dcmi_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dfsdm.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma2d.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dsi.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_eth.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ramfunc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_fmpi2c.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_fmpi2c_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_hash.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_hash_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_hcd.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_irda.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_iwdg.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_lptim.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_ltdc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_ltdc_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_mmc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_nand.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_nor.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pccard.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_qspi.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rng.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sai.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sai_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sd.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sdram.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_smartcard.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_spdifrx.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_spi.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sram.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim_ex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_uart.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_usart.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_wwdg.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_adc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_bus.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_cortex.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_crc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_dac.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_dma.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_dma2d.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_exti.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_fmc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_fsmc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_gpio.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_i2c.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_iwdg.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_lptim.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_pwr.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_rcc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_rng.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_rtc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_sdmmc.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_spi.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_system.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_tim.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_usart.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_usb.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_utils.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_wwdg.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F/portmacro.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/croutine.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/event_groups.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/FreeRTOS.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/list.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/portable.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/queue.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/StackMacros.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/task.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/timers.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/system_stm32f4xx.h \
    ../Middlewares/Third_Party/FatFs/src/diskio.h \
    ../Middlewares/Third_Party/FatFs/src/ff.h \
    ../Middlewares/Third_Party/FatFs/src/ff_gen_drv.h \
    ../Middlewares/Third_Party/FatFs/src/integer.h \
    ../Middlewares/Third_Party/FatFs/src/drivers/sd_diskio.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/api.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/arch.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/autoip.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/debug.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/def.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/dhcp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/dhcp6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/dns.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/err.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/errno.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/etharp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ethip6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/icmp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/icmp6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/igmp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/inet.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/inet_chksum.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/init.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ip.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ip_addr.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ip4.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ip4_addr.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ip4_frag.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ip6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ip6_addr.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/ip6_frag.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/mem.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/memp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/mld6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/nd6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/netbuf.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/netdb.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/netif.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/netifapi.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/opt.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/pbuf.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/raw.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/sio.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/snmp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/sockets.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/stats.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/sys.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/tcp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/tcpip.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/timeouts.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/udp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/priv/api_msg.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/priv/memp_priv.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/priv/memp_std.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/priv/tcp_priv.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/priv/tcpip_priv.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/etharp.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ethernet.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/lowpan6.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/lowpan6_opts.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/slipif.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/autoip.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/dhcp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/dns.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/etharp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/ethernet.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/icmp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/icmp6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/igmp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/ip.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/ip4.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/ip6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/mld6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/nd6.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/tcp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/prot/udp.h \
    ../Middlewares/Third_Party/LwIP/src/include/posix/errno.h \
    ../Middlewares/Third_Party/LwIP/src/include/posix/netdb.h \
    ../Middlewares/Third_Party/LwIP/system/arch/bpstruct.h \
    ../Middlewares/Third_Party/LwIP/system/arch/cc.h \
    ../Middlewares/Third_Party/LwIP/system/arch/cpu.h \
    ../Middlewares/Third_Party/LwIP/system/arch/epstruct.h \
    ../Middlewares/Third_Party/LwIP/system/arch/init.h \
    ../Middlewares/Third_Party/LwIP/system/arch/lib.h \
    ../Middlewares/Third_Party/LwIP/system/arch/perf.h \
    ../Middlewares/Third_Party/LwIP/system/arch/sys_arch.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/fs.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/httpd.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/httpd_opts.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/lwiperf.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/mdns.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/mdns_opts.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/mdns_priv.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/netbiosns.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/netbiosns_opts.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_core.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_mib2.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_opts.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_scalar.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_table.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_threadsync.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmpv3.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/sntp.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/sntp_opts.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/tftp_opts.h \
    ../Middlewares/Third_Party/LwIP/src/include/lwip/apps/tftp_server.h \
    ../Middlewares/Third_Party/LwIP/src/include/posix/sys/socket.h \
    ../Inc/quickSample.h \
    ../Inc/networktask.h \
    ../Inc/uartcomm/bufferred_uart.h \
    ../Inc/uartcomm/debug_print.h \
    ../Inc/uartcomm/putc_redirect.h \
    ../Inc/globals.h \
    ../Src/rx8025/Rx8025.h \
    ../Inc/gc-bsp.h \
    ../Src/keypad/keypad.h \
    ../Src/cs1238/cs1238.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f401xc.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f401xe.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f405xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f410cx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f410rx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f410tx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f411xe.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f412cx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f412rx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f412vx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f412zx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f413xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f415xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f417xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f423xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f427xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f429xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f437xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f439xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f446xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f469xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f479xx.h \
    ../Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h \
    ../Drivers/CMSIS/Include/arm_common_tables.h \
    ../Drivers/CMSIS/Include/arm_const_structs.h \
    ../Drivers/CMSIS/Include/arm_math.h \
    ../Drivers/CMSIS/Include/cmsis_armcc.h \
    ../Drivers/CMSIS/Include/cmsis_armcc_V6.h \
    ../Drivers/CMSIS/Include/cmsis_gcc.h \
    ../Drivers/CMSIS/Include/core_cm0.h \
    ../Drivers/CMSIS/Include/core_cm0plus.h \
    ../Drivers/CMSIS/Include/core_cm3.h \
    ../Drivers/CMSIS/Include/core_cm4.h \
    ../Drivers/CMSIS/Include/core_cm7.h \
    ../Drivers/CMSIS/Include/core_cmFunc.h \
    ../Drivers/CMSIS/Include/core_cmInstr.h \
    ../Drivers/CMSIS/Include/core_cmSimd.h \
    ../Drivers/CMSIS/Include/core_sc000.h \
    ../Drivers/CMSIS/Include/core_sc300.h \
    ../Drivers/CMSIS/RTOS/Template/cmsis_os.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h \
    ../Drivers/STM32F4xx_HAL_Driver/Inc/stm32_assert_template.h \
    ../MDK-ARM/RTE/_gc/RTE_Components.h \
    ../Middlewares/Third_Party/FatFs/src/drivers/sdram_diskio.h \
    ../Middlewares/Third_Party/FatFs/src/drivers/sram_diskio.h \
    ../Middlewares/Third_Party/FatFs/src/drivers/usbh_diskio.h \
    ../Middlewares/Third_Party/FatFs/src/ffconf_template.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/deprecated_definitions.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/FreeRTOSConfig_template.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/mpu_prototypes.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/mpu_wrappers.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/projdefs.h \
    ../Middlewares/Third_Party/FreeRTOS/Source/include/semphr.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/polarssl/arc4.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/polarssl/des.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/polarssl/md4.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/polarssl/md5.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/polarssl/sha1.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/ccp.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/chap-md5.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/chap-new.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/chap_ms.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/eap.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/ecp.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/eui64.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/fsm.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/ipcp.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/ipv6cp.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/lcp.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/magic.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/mppe.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/ppp.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/ppp_impl.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/ppp_opts.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppapi.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppcrypt.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppdebug.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppoe.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppol2tp.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppos.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/upap.h \
    ../Middlewares/Third_Party/LwIP/src/include/netif/ppp/vj.h

